version: '3.1'

services:
    nginx:
        build: 
            context: ./
            dockerfile: docker/nginx.docker
        restart: always
        volumes:
            - ./docker/nginx-wp.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www
        ports:
            - "8001:80"
        links:
            - php-fpm

    php-fpm:
        build: 
            context: ./
            dockerfile: docker/php-fpm.docker
        volumes:
            - ./:/var/www
            - ./logs:/var/log
        links:
            - mongo
            - rabbitmq

    mongo:
        image: mongo:latest
        restart: always
        ports:
            - 27017:27017
#        environment:
#            MONGO_INITDB_ROOT_USERNAME: rootlogin
#            MONGO_INITDB_ROOT_PASSWORD: rootpass

    rabbitmq:
        image: rabbitmq:alpine